## Data Prep

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

In [2]:
salmon_df = pd.read_csv(r"C:\Users\Owner\Documents\Graduate School\Fall 2026 Quarter\DATA 5100- Foundation of Data Science\Group Project\yukon_salmon.csv")
water_df = pd.read_csv(r"C:\Users\Owner\Documents\Graduate School\Fall 2026 Quarter\DATA 5100- Foundation of Data Science\Group Project\YukonWaterTemperature_vonFinster.csv", on_bad_lines = 'skip')

In [3]:
water_df.head()

     stationID    datetime.gmt  temperature
0  avf_09AB001   5/8/2011 9:00        4.428
1  avf_09AB001  5/8/2011 10:00        4.363
2  avf_09AB001  5/8/2011 11:00        4.311
3  avf_09AB001  5/8/2011 12:00        4.272
4  avf_09AB001  5/8/2011 13:00        4.272

In [4]:
water_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1022312 entries, 0 to 1022311
Data columns (total 3 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   stationID     1022312 non-null  str
 1   datetime.gmt  1022312 non-null  str
 2   temperature   1022286 non-null  float64
dtypes: float64(1), str(2)
memory usage: 48.3 MB

In [5]:
water_df["datetime.gmt"] = pd.to_datetime(water_df["datetime.gmt"],format = "%m/%d/%Y %H:%M")
water_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1022312 entries, 0 to 1022311
Data columns (total 3 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   stationID     1022312 non-null  str
 1   datetime.gmt  1022312 non-null  datetime64[us]
 2   temperature   1022286 non-null  float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 34.1 MB

In [6]:
water_df["stationID"].nunique()

20

In [7]:
by_station = water_df.groupby("stationID") #grouped data by 20 stations

In [8]:
by_year = pd.DataFrame(water_df.groupby(water_df["datetime.gmt"].dt.year)['temperature'].mean())#grouped by year

In [9]:
by_year.reset_index(inplace = True)
by_year

    datetime.gmt  temperature
0           2011     5.567316
1           2012     4.918484
2           2013     5.770873
3           2014     5.120191
4           2015     5.281110
5           2016     5.729688
6           2017     5.388590
7           2018     4.845551
8           2019     5.848474
9           2020     4.950968
10          2021     4.544293
11          2022     4.931812

In [10]:
by_year = by_year.rename(columns = {'datetime.gmt':'Year'})

In [11]:
by_year["Year"] = pd.to_datetime(by_year["Year"],format = "%Y")

In [12]:
by_year.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         12 non-null     datetime64[us]
 1   temperature  12 non-null     float64
dtypes: datetime64[us](1), float64(1)
memory usage: 324.0 bytes

In [13]:
salmon_df.head()

,Chapter,Region,Species,Year,Spawners,Harvest,Harvest Rate,Returns,Data Source
0,8,Yukon,Chinook,1982,35777,126408,0.779406,162185,YUKON JTC (25)-01 Appendix B11
1,8,Yukon,Chinook,1983,55250,127886,0.698312,183136,YUKON JTC (25)-01 Appendix B11
2,8,Yukon,Chinook,1984,68331,69967,0.505915,138298,YUKON JTC (25)-01 Appendix B11
3,8,Yukon,Chinook,1985,39082,119290,0.753227,158372,YUKON JTC (25)-01 Appendix B11
4,8,Yukon,Chinook,1986,49804,126371,0.717304,176175,YUKON JTC (25)-01 Appendix B11

In [14]:
salmon_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Chapter       70 non-null     int64
 1   Region        70 non-null     str
 2   Species       70 non-null     str
 3   Year          70 non-null     int64
 4   Spawners      70 non-null     int64
 5   Harvest       70 non-null     int64
 6   Harvest Rate  70 non-null     float64
 7   Returns       70 non-null     int64
 8   Data Source   70 non-null     str
dtypes: float64(1), int64(5), str(3)
memory usage: 8.2 KB

In [15]:
salmon_df = salmon_df[["Species", "Year", "Spawners", "Harvest", "Harvest Rate", "Returns"]]

In [16]:
salmon_df.tail()

   Species  Year  Spawners  Harvest  Harvest Rate  Returns
65    Chum  2020     23512     1488      0.059520    25000
66    Chum  2021     23170        0      0.000000    23000
67    Chum  2022     22034        0      0.000000    22000
68    Chum  2023     22090      910      0.039565    23000
69    Chum  2024     16174        0      0.000000    16000

merging Datasets

In [17]:
salmon_df["Year"] = pd.to_datetime(salmon_df["Year"],format = "%Y")

In [18]:
salmon_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Species       70 non-null     str
 1   Year          70 non-null     datetime64[us]
 2   Spawners      70 non-null     int64
 3   Harvest       70 non-null     int64
 4   Harvest Rate  70 non-null     float64
 5   Returns       70 non-null     int64
dtypes: datetime64[us](1), float64(1), int64(3), str(1)
memory usage: 3.8 KB

In [32]:
clean = by_year.merge(salmon_df, how = 'left', on= 'Year')
clean

         Year  temperature  Species  Spawners  Harvest  Harvest Rate  Returns
0  2011-01-01     5.567316  Chinook     47008    23489      0.333191    70497
1  2011-01-01     5.567316     Chum    205566   120434      0.369429   326000
2  2012-01-01     4.918484  Chinook     32328    19121      0.371650    51449
3  2012-01-01     4.918484     Chum    137662   100338      0.421588   238000
4  2013-01-01     5.770873  Chinook     28488    11129      0.280915    39617
5  2013-01-01     5.770873     Chum    200262   102738      0.339069   303000
6  2014-01-01     5.120191  Chinook     63370     1741      0.026739    65111
7  2014-01-01     5.120191     Chum    156796    66204      0.296879   223000
8  2015-01-01     5.281110  Chinook     82695     5646      0.063911    88341
9  2015-01-01     5.281110     Chum    108658    96342      0.469961   205000
10 2016-01-01     5.729688  Chinook     69164    14632      0.174615    83796
11 2016-01-01     5.729688     Chum    145267   152733      0.512527   298000
12 2017-01-01     5.388590  Chinook     69387    30559      0.305755    99946
13 2017-01-01     5.388590     Chum    401585   161415      0.286705   563000
14 2018-01-01     4.845551  Chinook     54595    22051      0.287699    76646
15 2018-01-01     4.845551     Chum    154126   124874      0.447577   279000
16 2019-01-01     5.848474  Chinook     42193    42955      0.504475    85148
17 2019-01-01     5.848474     Chum     99866    78134      0.438955   178000
18 2020-01-01     4.950968  Chinook     30646    21494      0.412236    52140
19 2020-01-01     4.950968     Chum     23512     1488      0.059520    25000
20 2021-01-01     4.544293  Chinook     31509     1730      0.052047    33239
21 2021-01-01     4.544293     Chum     23170        0      0.000000    23000
22 2022-01-01     4.931812  Chinook     12009     1351      0.101123    13360
23 2022-01-01     4.931812     Chum     22034        0      0.000000    22000

In [33]:
clean['temperature'].describe()

count    24.000000
mean      5.241446
std       0.412688
min       4.544293
25%       4.928480
50%       5.200650
75%       5.607909
max       5.848474
Name: temperature, dtype: float64

In [36]:
cleaned = clean.set_index(["Species"])
cleaned

              Year  temperature  Spawners  Harvest  Harvest Rate  Returns
Species
Chinook 2011-01-01     5.567316     47008    23489      0.333191    70497
Chum    2011-01-01     5.567316    205566   120434      0.369429   326000
Chinook 2012-01-01     4.918484     32328    19121      0.371650    51449
Chum    2012-01-01     4.918484    137662   100338      0.421588   238000
Chinook 2013-01-01     5.770873     28488    11129      0.280915    39617
Chum    2013-01-01     5.770873    200262   102738      0.339069   303000
Chinook 2014-01-01     5.120191     63370     1741      0.026739    65111
Chum    2014-01-01     5.120191    156796    66204      0.296879   223000
Chinook 2015-01-01     5.281110     82695     5646      0.063911    88341
Chum    2015-01-01     5.281110    108658    96342      0.469961   205000
Chinook 2016-01-01     5.729688     69164    14632      0.174615    83796
Chum    2016-01-01     5.729688    145267   152733      0.512527   298000
Chinook 2017-01-01     5.388590     69387    30559      0.305755    99946
Chum    2017-01-01     5.388590    401585   161415      0.286705   563000
Chinook 2018-01-01     4.845551     54595    22051      0.287699    76646
Chum    2018-01-01     4.845551    154126   124874      0.447577   279000
Chinook 2019-01-01     5.848474     42193    42955      0.504475    85148
Chum    2019-01-01     5.848474     99866    78134      0.438955   178000
Chinook 2020-01-01     4.950968     30646    21494      0.412236    52140
Chum    2020-01-01     4.950968     23512     1488      0.059520    25000
Chinook 2021-01-01     4.544293     31509     1730      0.052047    33239
Chum    2021-01-01     4.544293     23170        0      0.000000    23000
Chinook 2022-01-01     4.931812     12009     1351      0.101123    13360
Chum    2022-01-01     4.931812     22034        0      0.000000    22000

In [37]:
clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          24 non-null     datetime64[us]
 1   temperature   24 non-null     float64
 2   Species       24 non-null     str
 3   Spawners      24 non-null     int64
 4   Harvest       24 non-null     int64
 5   Harvest Rate  24 non-null     float64
 6   Returns       24 non-null     int64
dtypes: datetime64[us](1), float64(2), int64(3), str(1)
memory usage: 1.6 KB

In [47]:
clean.to_csv(r'C:\Users\Owner\Documents\Graduate School\Fall 2026 Quarter\DATA 5100- Foundation of Data Science\Group Project\water_salmon_clean.csv', encoding = 'utf-8-sig', index = False)